# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

react_native_path = '../node_modules/react-native'

target 'react-native-svg-charts' do

  # Pods for react-native-svg-charts

  # Below section of pods are required by 'CxxBridge'
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'CxxBridge',
  'Core',
  'RCTAnimation',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTBlob',
  'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
